#pragma once

/* This file is automatically generated by prebuilt events (tools/determine_cdkversion.bat) */
#include <CDKVersion_generated.tmp>

/* SDK Version detection */
#if CDK_VERSION >= 510
#define USE_NEW_INCLUDE_PATHS 1
#else
#define USE_NEW_INCLUDE_PATHS 0
#endif
