:: This is an prebuilt script part of the Plugin SDK
@echo off

cd %~dp0

set dynheaderfile=../inc/CDKVersion_generated.tmp

FOR /F "tokens=1-3 delims=, " %%A IN ('sigcheck -n -q ../../../Bin32/CrySystem.dll') DO (
  echo Plugin SDK detected CryEngine %%~A.%%~B.%%~C

  echo /* This file was automatically generated by determine_cdkversion.bat */> %dynheaderfile%
  echo #define CDK_VERSION_DETERMINED>> %dynheaderfile%
  echo #define CDK_VERSION %%~A%%~B%%~C>> %dynheaderfile%
  echo #define PLUGIN_COMPILED_CDK_VERSION "%%~A.%%~B.%%~C">> %dynheaderfile%  
)