:: This is an prebuilt script part of the Plugin SDK
::@echo off

set "dynheaderfile=%~dp0..\inc\CDKVersion_generated.tmp"
set "tempvers=%~dp0tempvers.tmp"

if exist "%~dp0..\..\..\Bin64\CrySystem.dll" (
  "%~dp0sigcheck.exe" -n -q "%~dp0..\..\..\Bin64\CrySystem.dll" > "%tempvers%"
)

if exist "%~dp0..\..\..\Bin32\CrySystem.dll" (
  "%~dp0sigcheck.exe" -n -q "%~dp0..\..\..\Bin32\CrySystem.dll" > "%tempvers%"
)

if exist "%~dp0..\..\..\bin\win_x64_release\CrySystem.dll" (
  "%~dp0sigcheck.exe" -n -q "%~dp0..\..\..\bin\win_x64_release\CrySystem.dll" > "%tempvers%"
)

if exist "%~dp0..\..\..\bin\win_x86_release\CrySystem.dll" (
  "%~dp0sigcheck.exe" -n -q "%~dp0..\..\..\bin\win_x86_release\CrySystem.dll" > "%tempvers%"
)

if exist "%~dp0..\..\..\bin\win_x64\CrySystem.dll" (
  "%~dp0sigcheck.exe" -n -q "%~dp0..\..\..\bin\win_x64\CrySystem.dll" > "%tempvers%"
)

if exist "%~dp0..\..\..\bin\win_x86\CrySystem.dll" (
  "%~dp0sigcheck.exe" -n -q "%~dp0..\..\..\bin\win_x86\CrySystem.dll" > "%tempvers%"
)

for /f "usebackq tokens=1-3 delims=, " %%A in ("%tempvers%") do (
  echo Plugin SDK detected CryEngine %%~A.%%~B.%%~C

  echo /* This file was automatically generated by determine_cdkversion.bat */> "%dynheaderfile%"
  echo #define CDK_VERSION_DETERMINED>> "%dynheaderfile%"
  echo #define CDK_VERSION %%~A%%~B%%~C>> "%dynheaderfile%"
  echo #define PLUGIN_COMPILED_CDK_VERSION "%%~A.%%~B.%%~C">> "%dynheaderfile%"
)